// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzszjufttrntzlrevzrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6c3pqdWZ0dHJudHpscmV2enJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MjA5NTgsImV4cCI6MjA1ODQ5Njk1OH0.dE23hayBbgkUFm0XsfrQN5D1KLwE6SfOfeM6HkTII28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);